# Generated by Django 4.1.9 on 2024-03-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swalookuserprofile',
            name='account_created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vendorappointment',
            name='status_canceled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorappointment',
            name='status_completed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorappointment',
            name='status_pending',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
