# Generated by Django 4.1.9 on 2024-03-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_api_', '0002_alter_swalookuserprofile_account_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorappointment',
            name='price',
        ),
        migrations.RemoveField(
            model_name='vendorappointment',
            name='status_canceled',
        ),
        migrations.RemoveField(
            model_name='vendorappointment',
            name='status_completed',
        ),
        migrations.RemoveField(
            model_name='vendorappointment',
            name='status_pending',
        ),
        migrations.AlterField(
            model_name='vendorappointment',
            name='booking_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
